# theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
timezone: Asia/Taipei
author: Lí Ka-io̍k
title: wox080xow's home page
description: Bookmark this to keep an eye on my project updates!
